name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tsc:
    name: compiling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
        with:
          node-version: 16.15.1
      - run: npm i
      - run: npm run tsc
  build:
    name: building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm i
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: pwa-build
          path: qwixx-pwa/out
  deploy:
    needs: [tsc, build]
    name: deploying pwa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pwa-build
          path: out
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder'
      - run: ssh-keyscan -H ${{ secrets.HETZNER_SERVER_IP }} >> ~/.ssh/known_hosts
      - run: scp -r ./out/* ${{ secrets.HETZNER_SERVER_USER }}@${{ secrets.HETZNER_SERVER_IP }}:/var/www/qwixx
