on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please-pwa:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
          # this is a built-in strategy in release-please
          # for more options: https://github.com/googleapis/release-please-action?tab=readme-ov-file#action-inputs
          release-type: node
          path: qwixx-pwa
